import { useState } from "react";
import { useAppContext } from "../../../app/AppContext";
import { PageHeader } from "../../../components/layout/PageHeader";
import { Button } from "../../../components/ui/Button";
import { importantChangeSnapshot } from "../../../data/fixtures/demoInvestment";

export function ChangePage() {
  const { navigate } = useAppContext();
  const [step, setStep] = useState(0);
  const [update, setUpdate] = useState("保持目前判斷");
  return <section><PageHeader eyebrow="重要變化與理解更新" title="理解變化，再決定是否更新判斷" description="先還原原始脈絡，再讓使用者決定下一步。" /><div className="change-flow-tabs">{["發生什麼", "AI 解讀", "更新理解"].map((label, index) => <button key={label} className={step === index ? "active" : ""} onClick={() => setStep(index)}><span>{index + 1}</span>{label}</button>)}</div>{step === 0 && <article className="change-stage card"><span className="severity attention">{importantChangeSnapshot.severity}層級</span><h2>{importantChangeSnapshot.title}</h2><p>資料來源：<a href={importantChangeSnapshot.source.url} target="_blank" rel="noreferrer">{importantChangeSnapshot.source.publisher}・{importantChangeSnapshot.source.title}</a>（資料截至 {importantChangeSnapshot.dataAsOf}）。</p><div className="impact-chain"><div><span>發生什麼</span><strong>{importantChangeSnapshot.happened}</strong></div><b>→</b><div><span>影響哪個原始假設</span><strong>{importantChangeSnapshot.assumption}</strong></div><b>→</b><div><span>與我的目標有何關聯</span><strong>{importantChangeSnapshot.goalImpact}</strong></div></div><Button onClick={() => setStep(1)}>了解這項變化 →</Button></article>}{step === 1 && <article className="change-stage card"><span className="ai-spark">✦</span><span className="card-label">基於官方資料的結構化解讀</span><h2>獲利率展望可能正常化，但尚不足以否定長期需求假設</h2><div className="ai-structure"><div><b>01</b><strong>已確認變化</strong><small>Q2 實際 67.7%；Q3 展望 65%–67%</small></div><div><b>02</b><strong>受影響假設</strong><small>技術領先與產能管理能維持獲利品質</small></div><div><b>03</b><strong>個人影響</strong><small>單一個股成長投資需持續觀察</small></div><div><b>04</b><strong>下一步</strong><small>等待 Q3 實際結果並比較，不提供買賣指令</small></div></div><Button onClick={() => setStep(2)}>更新我的投資理解 →</Button></article>}{step === 2 && <article className="change-stage card"><span className="card-label">更新選項</span><h2>根據新資訊，選擇如何更新</h2><div className="update-options">{["保持目前判斷", "更新投資理由", "更新觀察條件", "調整投資規劃"].map((option) => <label key={option}><input type="radio" name="update" checked={update === option} onChange={() => setUpdate(option)} /><span><strong>{option}</strong><small>記錄使用者選擇，保留完整更新脈絡。</small></span></label>)}</div><Button onClick={() => navigate("tracking")}>完成更新並持續追蹤 →</Button></article>}</section>;
}
