import { useState } from "react";
import type { InvestmentData } from "../../../hooks/useInvestmentData";
import { useAppContext } from "../../../app/AppContext";
import { PageHeader } from "../../../components/layout/PageHeader";
import { Button } from "../../../components/ui/Button";

export function ExplorePage({ data }: { data: InvestmentData }) {
  const { navigate, openAssistant } = useAppContext();
  const [tab, setTab] = useState<"directions" | "candidates">("directions");
  return <section><PageHeader eyebrow="Screen 07–08｜方向探索與候選標的" title="從規劃出發，找到研究方向" description="候選內容代表值得進一步研究，不代表系統要求購買。" action={<Button variant="ghost" onClick={() => openAssistant("請幫我比較這些方向")}>✦ 請 AI 協助比較</Button>} /><div className="tabs" role="tablist"><button className={tab === "directions" ? "active" : ""} onClick={() => setTab("directions")}>投資方向</button><button className={tab === "candidates" ? "active" : ""} onClick={() => setTab("candidates")}>候選標的</button></div>{tab === "directions" ? <div className="direction-grid"><article className="card direction-card"><span className="direction-code">方向 01｜核心配置</span><h2>分散型多資產核心</h2><p>對應八年目標與穩健風險意願，優先降低單一市場依賴。</p><dl><div><dt>與目標的關聯</dt><dd>提高路徑穩定性</dd></div><div><dt>主要觀察</dt><dd>資產相關性</dd></div></dl><Button variant="secondary" onClick={() => setTab("candidates")}>查看候選標的 →</Button></article><article className="card direction-card"><span className="direction-code">方向 02｜成長配置</span><h2>品質成長研究</h2><p>保留適度成長性，同時以獲利品質與集中度作為限制。</p><dl><div><dt>與目標的關聯</dt><dd>補足成長需求</dd></div><div><dt>主要觀察</dt><dd>估值與集中度</dd></div></dl><Button variant="secondary" onClick={() => setTab("candidates")}>查看候選標的 →</Button></article></div> : <div className="candidate-list">{data.candidates.map((candidate) => <article className="card candidate" key={candidate.id}><div className="candidate-main"><span className="ticker">{candidate.symbol}</span><div><span className="card-label">{candidate.category}</span><h2>{candidate.name}</h2><p>{candidate.rationale}</p></div></div><div className="candidate-reasons"><div><span>研究條件符合度</span><strong>{candidate.researchFit}/100</strong></div><div><span>個人初步適合度</span><strong>{candidate.suitability}/100</strong></div></div><Button onClick={() => navigate("instrument")}>查看詳細分析 →</Button></article>)}</div>}</section>;
}
