import type { InvestmentData } from "../../../hooks/useInvestmentData";
import { useAppContext } from "../../../app/AppContext";
import { PageHeader } from "../../../components/layout/PageHeader";
import { Button } from "../../../components/ui/Button";
import { importantChangeSnapshot } from "../../../data/fixtures/demoInvestment";

const money = new Intl.NumberFormat("zh-TW", { style: "currency", currency: "TWD", maximumFractionDigits: 0 });

export function HomePage({ data }: { data: InvestmentData }) {
  const { navigate, openAssistant } = useAppContext();
  const progress = Math.round((data.goal.currentAmount / data.goal.targetAmount) * 100);
  return <section><PageHeader eyebrow="回訪首頁｜決策總覽" title="今天，從最重要的下一步開始" description="聚焦你的目標、規劃、論點與重要變化，不呈現市場噪音。" action={<Button onClick={() => navigate("explore")}>繼續研究 →</Button>} /><div className="dashboard-grid"><article className="card goal-card"><div className="card-head"><div><span className="card-label">我的目標</span><h2>{data.goal.name}</h2></div><button className="text-button" onClick={() => navigate("onboarding")}>編輯</button></div><div className="goal-ring" style={{ "--progress": `${progress * 3.6}deg` } as React.CSSProperties}><span>{progress}%</span><small>目前進度</small></div><p>{data.goal.years} 年後累積 {money.format(data.goal.targetAmount)}，每月投入 {money.format(data.goal.monthlyContribution)}。</p></article><article className="card next-card"><span className="card-label">建議下一步</span><h2>檢視台積電最新獲利率展望</h2><p>{importantChangeSnapshot.title}，值得回到原始假設確認。</p><Button onClick={() => navigate("change")}>查看重要變化 →</Button></article><article className="card"><div className="card-head"><div><span className="card-label">我的投資規劃</span><h3>三層資金結構</h3></div><span className="status stable">已建立</span></div><p>核心 {data.allocations[0].percentage}%・成長 {data.allocations[1].percentage}%・彈性 {data.allocations[2].percentage}%</p><button className="text-button" onClick={() => navigate("plan")}>查看完整規劃 →</button></article><article className="card"><div className="card-head"><div><span className="card-label">我的論點</span><h3>{data.thesis.status}</h3></div><span className="status neutral">1</span></div><p>{data.thesis.reason}</p><button className="text-button" onClick={() => navigate("thesis")}>查看論點卡 →</button></article><article className="card"><div className="card-head"><div><span className="card-label">心跳追蹤</span><h3>1 項需要理解</h3></div><span className="status attention">注意</span></div><p>台積電已公布第三季毛利率展望，可能影響原始獲利能力假設。</p><button className="text-button" onClick={() => navigate("tracking")}>前往追蹤中心 →</button></article><article className="card ai-home"><span className="ai-spark">✦</span><div><span className="card-label">AI 決策陪伴</span><h3>今天想了解什麼？</h3><p>AI 會承接目前畫面；Version 1 使用前端 Demo 回覆。</p></div><Button variant="secondary" onClick={() => openAssistant()}>開始對話</Button></article></div></section>;
}
